package triaje;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-11T16:45:42.040-04:30
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "SosTriajeService", 
                  wsdlLocation = "docs/sostriaje5.wsdl",
                  targetNamespace = "http://triaje/") 
public class SosTriajeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://triaje/", "SosTriajeService");
    public final static QName SosTriajeServicePort = new QName("http://triaje/", "SosTriajeServicePort");
    static {
        URL url = SosTriajeService.class.getResource("docs/sostriaje5.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SosTriajeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "docs/sostriaje5.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SosTriajeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SosTriajeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SosTriajeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SosTriajeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SosTriajeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SosTriajeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SosTriajeServicePortType
     */
    @WebEndpoint(name = "SosTriajeServicePort")
    public SosTriajeServicePortType getSosTriajeServicePort() {
        return super.getPort(SosTriajeServicePort, SosTriajeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SosTriajeServicePortType
     */
    @WebEndpoint(name = "SosTriajeServicePort")
    public SosTriajeServicePortType getSosTriajeServicePort(WebServiceFeature... features) {
        return super.getPort(SosTriajeServicePort, SosTriajeServicePortType.class, features);
    }

}
